### ISSUE TITLE
Error No rule to make target 'package/*/download'

### ISSUE THREAD

**Issue by robberphex** [openwrt/gh-action-sdk#26]
I tried use `openwrt/gh-action-sdk` to build [luci-app-v2ray](https://github.com/robberphex/luci-app-v2ray).
Use this step:
```yml
      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
          FEED_DIR: ${{ github.workspace }}
          PACKAGES: ${{ env.PACKAGE_NAME }}
```

It failed with message:
```
...
Config-build.in:907:warning: defaults for choice values not supported
#
# No change to .config
#
make[1]: Entering directory '/builder'
make[1]: *** No rule to make target 'package/luci-app-v2ray/download'.  Stop.
make[1]: Leaving directory '/builder'
make: *** [/builder/include/toplevel.mk:223: package/luci-app-v2ray/download] Error 2
Error: Process completed with exit code 2.
```

The full log <https://github.com/robberphex/luci-app-v2ray/actions/runs/5048885064/jobs/9057636952>.
Log archive [logs_45.zip](https://github.com/openwrt/gh-action-sdk/files/11534695/logs_45.zip).
